name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-release:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the Tag and set the Version
        id: get_tag
        shell: bash
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Run build and publish tasks
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          set -e -x
          export DOCKER_IMAGE_TAG_OVERRIDE=${TAG}
          echo $DOCKER_IMAGE_TAG_OVERRIDE
          echo "Building main and package-tooling..."
          make DOCKER_IMAGE_TAG_OVERRIDE=$DOCKER_IMAGE_TAG_OVERRIDE build
          echo "publishing main and package-tooling..."
          make DOCKER_IMAGE_TAG_OVERRIDE=$DOCKER_IMAGE_TAG_OVERRIDE publish
      - name: Release
        uses: softprops/action-gh-release@v1
