name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the Tag and set the Version
        id: get_tag
        shell: bash
        run: echo ::set-output name=tag::${{GITHUB_REF#refs/*/}}
      - name: Echo Tag
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          echo "TAG: ${TAG}"
      - name: Run build and publish tasks
        run: |
          set -e -x
          export DOCKER_IMAGE_TAG_OVERRIDE=`cat version.txt`
          echo $DOCKER_IMAGE_TAG_OVERRIDE
          echo "Building..."
          make DOCKER_IMAGE_TAG_OVERRIDE=$DOCKER_IMAGE_TAG_OVERRIDE build
          echo "publishing..."
          make DOCKER_IMAGE_TAG_OVERRIDE=$DOCKER_IMAGE_TAG_OVERRIDE publish
      - name: Release
        uses: softprops/action-gh-release@v1
